### PR TITLE
Enter API Key Option

### PR DESCRIPTION
**Pull request by mdhsieh**
A section to enter user's own API key mentioned in #13. With an option to either use the key or reset to the default key like with buttons. Using local storage to save keys.

Screenshot 2024-11-13 at 4 29 11 PM

### CODE REVIEW

**Comment by knightron0** [comment]
this is great! a few thoughts:
- it should be more obvious that it's not _required_ for the user to enter their own API key
- a lot of users also won't know how to create one – we can have documentation that details how to do that (which permissions to select, etc)

thanks for the PR! i can also take a look at integrating some of these, i'll checkout your version to a branch and work off it.

**Comment by mdhsieh** [comment]
Ooh yeah, let's fix that. Maybe label that it's optional, and instead of buttons have a switch that's off by default? And then have a link to an updated readme.

**Comment by knightron0** [comment]
yeah that's perfect – thanks so much again :)

**Comment by mdhsieh** [comment]
Something like this:

Screenshot 2024-11-14 at 5 44 38 PM

**Comment by knightron0** [comment]
this looks good! i'm going to merge this to another branch – i have a few tweaks to push as well.

thank you so much!

**Comment by knightron0** [comment]
let me know if everything in #17 looks good - i'll go ahead and publish to the chrome store then.

it's more practical if we have the API key field input in the popup which says "Tempus is currently fetching.." as well (this is showed when the extension doesn't work)

**Comment by mdhsieh** [comment]
Yup #17 looks good to me.

**Pull request merged**
